---
general:
  buildTool: "mta"
  deployTool: "mtaDeployPlugin"

# Steps configuration
steps:
  mtaBuild:
    buildTarget: "CF"
  cloudFoundryDeploy:
    apiEndpoint: "https://api.cf.ap10.hana.ondemand.com"
    org: "secondphase"
    space: "dev"

  # tmsUpload:
  #   nodeName: "QA_MTA"
  #   credentialsId: "tms-sk"
