---
general:
  buildTool: "mta"
  deployTool: "mtaDeployPlugin"

# Steps configuration
steps:
  mtaBuild:
    buildTarget: "CF"
    mtarName: helloworld.mtar
  cloudFoundryDeploy:
    buildTool: "mta"
    deployTool: "mtaDeployPlugin"
    apiEndpoint: "https://api.cf.ap10.hana.ondemand.com"
    mtaPath: ./helloworld.mtar
    org: "secondphase"
    space: "dev"

  # tmsUpload:
  #   nodeName: "QA_MTA"
  #   credentialsId: "tms-sk"
