---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    tmsUpload: true
    cfApiEndpoint: "https://api.cf.ap10.hana.ondemand.com"
    cfOrg: "secondphase"
    cfSpace: "dev"
    cfAppName: "helloworld"

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "QA_MTA"
    credentialsId: "tms-sk"
