---
general:
  buildTool: "mta"

steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    apiEndpoint: "https://api.cf.ap10.hana.ondemand.com"
    org: "secondphase"
    space: "dev"

  # tmsUpload:
  #   nodeName: "QA_MTA"
  #   credentialsId: "tms-sk"
