name: CI

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cloudFoundryDeploy
        uses: SAP/project-piper-action@master
        with:
          command: cloudFoundryDeploy
          piper-version: master
        env:
          PIPER_username: ${{ secrets.USERNAME }}
          PIPER_password: ${{ secrets.PASSWORD }}